inherit_from: "configs/stereo/tartanair/base_config.yaml"

Dataset:
  dataset_path: "/home/shiyo/Desktop/Datasets/TartanAir_Stereo_Challenge/stereo/SE000"

  # Optional override. If omitted, the loader automatically checks:
  #   1) <dataset_path>/pose_left.txt
  #   2) <dataset_path>/SE000.txt
  #   3) /home/shiyo/Desktop/Datasets/TartanAir_Stereo_Challenge/stereo_gt/SE000.txt
  # pose_file: "/home/shiyo/Desktop/Datasets/TartanAir_Stereo_Challenge/stereo_gt/SE000.txt"

  start_idx: 0
  end_idx: -1
  frame_stride: 1
